name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git openjdk-8-jdk python3-pip

      - name: Install Python for Android (p4a)
        run: pip3 install python-for-android



      - name: Build APK
        run: |
          p4a apk --private . --package org.downloader.app --name "Instadownloader" --version 1.0 --requirements=python3,kivy,selenium,requests, --dist_name instadownloader --permission INTERNET,WRITE_EXTERNAL_STORAGE --icon images/logo.png --arch armeabi-v7a
